### ISSUE TITLE
io.enmasse.systemtest.brokered.web.FirefoxWebConsoleTest.testViewAddresses fails on Incorrect results value! expected: '1', got: '0'

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#1092] opened 2018-03-23 08:57 UTC
java.lang.AssertionError: Incorrect results value! expected: '1', got: '0'
	at io.enmasse.systemtest.brokered.web.FirefoxWebConsoleTest.testViewAddresses(FirefoxWebConsoleTest.java:107)

Test logs and reports attached

[archive.zip](https://github.com/EnMasseProject/enmasse/files/1840776/archive.zip)

**Comment by kornys** [comment] 2018-03-27 05:49
Problem was caused by missing addresses in address web page. Looks like user had no rights to view those addresses. I will investigate why. Anyway this issue is no longer appear.

**Comment by kornys** [comment] 2018-03-27 13:20
I cannot reproduce this issue. I'm closing it. Will be reopened when issue appear

**Closed by kornys** 2018-03-27 13:20 UTC
