### ISSUE TITLE
mqtt (standard-space): interoperability - send amqp, receive mqtt doesn't work

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#1103] opened 2018-03-27 11:37 UTC
As @lulf mentioned last week that amqp mqtt interoperability doesn't work. So there are some additional informations and automated reproducer.

**Description:**
Send Amqp message and receive Mqtt message doesn't work in standard-address space (in opposite direction it works fine). 

**Logs:**
client was subscribed successfully:
```
11:21:47.518 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttGateway - CONNECT from MQTT client 922fcd21-c213-483f-9fde-a40cf386d538
11:21:47.619 [vert.x-eventloop-thread-0] INFO  e.m.e.AmqpSubscriptionServiceEndpoint - AMQP close delivery Accepted{}
11:21:47.620 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - CONNACK to MQTT client 922fcd21-c213-483f-9fde-a40cf386d538 [accepted]
11:21:47.620 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttGateway - Opened AMQP bridge for client 922fcd21-c213-483f-9fde-a40cf386d538
11:21:47.629 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - SUBSCRIBE [1] from MQTT client 922fcd21-c213-483f-9fde-a40cf386d538
11:21:47.710 [vert.x-eventloop-thread-0] INFO  e.m.e.AmqpSubscriptionServiceEndpoint - AMQP subscribe delivery Accepted{}
11:21:47.711 [vert.x-eventloop-thread-0] INFO enmasse.mqtt.AmqpBridge - SUBACK [1] to MQTT client 922fcd21-c213-483f-9fde-a40cf386d538
```

sender send messages
and in log of mqtt-gateway we can see that messages were processed (but never arrived to the subscriber)
```
11:21:48.158 [vert.x-eventloop-thread-0] INFO  e.m.endpoints.AmqpReceiverEndpoint - Received Message{properties=Properties{messageId=AmqpValue{0}, userId=null, to='amqp-mqtt-topic', subject='mysubject', replyTo='null', correlationId=null, contentType=null, contentEncoding=null, absoluteExpiryTime=null, creationTime=null, groupId='null', groupSequence=null, replyToGroupId='null'}message_annotations=MessageAnnotations{{_AMQ_ORIG_ADDRESS=amqp-mqtt-topic, _AMQ_ORIG_MESSAGE_ID=54057}}body=AmqpValue{send mqtt, receive amqp :)-0}}
11:21:48.164 [vert.x-eventloop-thread-0] INFO  e.m.endpoints.AmqpReceiverEndpoint - Received Message{properties=Properties{messageId=AmqpValue{1}, userId=null, to='amqp-mqtt-topic', subject='mysubject', replyTo='null', correlationId=null, contentType=null, contentEncoding=null, absoluteExpiryTime=null, creationTime=null, groupId='null', groupSequence=null, replyToGroupId='null'}message_annotations=MessageAnnotations{{_AMQ_ORIG_ADDRESS=amqp-mqtt-topic, _AMQ_ORIG_MESSAGE_ID=54065}}body=AmqpValue{send mqtt, receive amqp :)-1}}
11:21:48.170 [vert.x-eventloop-thread-0] INFO  e.m.endpoints.AmqpReceiverEndpoint - Received Message{properties=Properties{messageId=AmqpValue{2}, userId=null, to='amqp-mqtt-topic', subject='mysubject', replyTo='null', correlationId=null, contentType=null, contentEncoding=null, absoluteExpiryTime=null, creationTime=null, groupId='null', groupSequence=null, replyToGroupId='null'}message_annotations=MessageAnnotations{{_AMQ_ORIG_ADDRESS=amqp-mqtt-topic, _AMQ_ORIG_MESSAGE_ID=54073}}body=AmqpValue{send mqtt, receive amqp :)-2}}
11:21:48.175 [vert.x-eventloop-thread-0] INFO e.m.endpoints.AmqpReceiverEndpoint - Received Message{properties=Properties{messageId=AmqpValue{3}, userId=null, to='amqp-mqtt-topic', subject='mysubject', replyTo='null', correlationId=null, contentType=null, contentEncoding=null, absoluteExpiryTime=null, creationTime=null, groupId='null', groupSequence=null, replyToGroupId='null'}message_annotations=MessageAnnotations{{_AMQ_ORIG_ADDRESS=amqp-mqtt-topic, _AMQ_ORIG_MESSAGE_ID=54080}}body=AmqpValue{send mqtt, receive amqp :)-3}}
```
then connection is closed:
```
11:22:48.284 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - DISCONNECT from MQTT client 922fcd21-c213-483f-9fde-a40cf386d538
11:22:48.285 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - Close from MQTT client 922fcd21-c213-483f-9fde-a40cf386d538
11:22:48.286 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttGateway - Closed AMQP bridge for client 922fcd21-c213-483f-9fde-a40cf386d538
11:22:48.286 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - AMQP connection closed with Router.qdrouterd-1763894153-bzzz2
11:22:48.286 [vert.x-eventloop-thread-0] WARN  enmasse.mqtt.AmqpBridge - MQTT endpoint for client 922fcd21-c213-483f-9fde-a40cf386d538 already closed
11:22:48.286 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - AMQP disconnection with Router.qdrouterd-1763894153-bzzz2
11:22:48.287 [vert.x-eventloop-thread-0] WARN enmasse.mqtt.AmqpBridge - MQTT endpoint for client 922fcd21-c213-483f-9fde-a40cf386d538 already closed
```

**Automated test:** (test is disabled in master branch)
`make MULTITENANT=true SYSTEMTEST_ARGS='InteroperabilityTest#testSendAmqpReceiveMqtt' systemtests`

**Comment by k-wall** [comment] 2018-08-24 17:47
I encountered this `@Disabled` test during work on 
https://github.com/EnMasseProject/enmasse/pull/1531.  The issue is the handling of the AMQP subject.  I raised a specific issue 
https://github.com/EnMasseProject/enmasse/issues/1528 as I did not realise this one existed.

Closing this issue.

**Closed by k-wall** 2018-08-24 17:47 UTC
Labels: kind/bug
