### ISSUE TITLE
"Admin" pod fails with OOM error

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#382] opened 2017-10-20 13:08 UTC
We have deployed EnMasse 0.13.2 in Kubernetes. 
The "admin" Pod with the EnMasse console keeps on restarting because of an out of memory error.

From the "kubectl describe pod" command:
````
  console:
    Container ID:   docker://5e392fc04e7bfc222cb8a69a491b854a4ae4efcb0686933d715f2a4572857e29
    Image:          docker.io/enmasseproject/console:0.13.2
    Image ID:       docker-pullable://enmasseproject/console@sha256:8f7be12a319fde76215282c2c85850319aae79d5b24177dfc094f6c0a5c6d815
    Ports:          8080/TCP, 56720/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Fri, 20 Oct 2017 10:58:53 +0200
      Finished:     Fri, 20 Oct 2017 10:59:33 +0200
    Ready:          False
    Restart Count:  201
    Limits:
      memory:  64Mi
    Requests:
      memory:  64Mi
    Liveness:  tcp-socket :http delay=60s timeout=1s period=10s #success=1 #failure=3
````

Having a look inside the container reveals this:
````
$ kubectl exec admin-136398735-h73x1 -n hono -c console -- ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  5.1  1.8 1149876 75556 ?       Ssl  12:49   0:02 node /opt/app-root/src/bin/console_server.js
root        50  0.0  0.0  47452  3116 ?        Rs   12:50   0:00 ps aux
````
and
````
$ kubectl exec admin-136398735-h73x1 -n hono -c console -- cat /proc/1/status
Name:	node
State:	S (sleeping)
Tgid:	1
Ngid:	0
Pid:	1
PPid:	0
TracerPid:	0
Uid:	0	0	0	0
Gid:	0	0	0	0
FDSize:	256
Groups:	
NStgid:	1
NSpid:	1
NSpgid:	1
NSsid:	1
VmPeak:	 1174896 kB
VmSize:	 1147944 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	   67536 kB
VmRSS:	   67536 kB
VmData:	 1045996 kB
VmStk:	     140 kB
VmExe:	   15584 kB
VmLib:	   32380 kB
VmPTE:	     464 kB
VmPMD:	     228 kB
VmSwap:	       0 kB
HugetlbPages:	       0 kB
Threads:	10
SigQ:	0/15739
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000001000
SigCgt:	0000000180004202
CapInh:	00000000a80425fb
CapPrm:	00000000a80425fb
CapEff:	00000000a80425fb
CapBnd:	00000000a80425fb
CapAmb:	0000000000000000
Seccomp:	0
Cpus_allowed:	0003
Cpus_allowed_list:	0-1
Mems_allowed:	00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	464
nonvoluntary_ctxt_switches:	315
````

**Comment by lulf** [comment] 2017-10-20 13:31
75556 is clearly above 64k of memory, so i guess this is why it gets killed. You can edit the admin deployment and change the console container resource requirements to:

```
     "resources": {                                                                                                                                                                                           
          "requests": {                                                                                                                                                                                          
            "memory": "128Mi",                                                                                                                                                                                    
          },                                                                                                                                                                                                     
          "limits": {                                                                                                                                                                                            
            "memory": "128Mi",                                                                                                                                                                                    
          }                                                                                                                                                                                                      
       },         
```

Then we will increase the default limits.

**Comment by lulf** [comment] 2017-10-25 11:57
Closing for now as I've doubled the default limits. Reopen if it happens again.

**Closed by lulf** 2017-10-25 11:57 UTC
Labels: bug

**Comment by calohmn** [comment] 2017-11-01 14:17
A further note on this: 
the fact that the "admin" POD not only contains the "console" container with the memory issue, but also other containers like the "ragent" has caused further issues for us. 
The frequent restarts of the "ragent" container due to the failing "console" container have led to issues with Addresses being absent intermittently which led to anycast being used instead of multicast (as defined in our Addresses). 
In order to not have such effects between the UI component and the ragent, would it be feasable to move the "console" container into its own pod?

**Comment by lulf** [comment] 2017-11-01 14:22
We were originally running the containers in the 'admin' pod inside their own pods, but moved them into the admin pod again to accomodate typical quota limits found on OpenShift online for instance.

However, I do think your point is valid, and that we should consider at minimum moving the console container into its own pod, as it is useful from a monitoring perspective (i.e. it could show an error if ragent is not correctly configured).

@grs Any thoughts on this suggestion?

**Comment by grs** [comment] 2017-11-01 14:41
I'm not sure why addresses would be absent due to the ragent being restarted. The ragent is of course necessary for the address to be deployed correctly, and the status of the address should not by marked ready until this has been done. However after that, if the ragent is not there, the address should remain. Restarting a router (or adding a new router) would require the ragent before it could be connected to the other agents or have the addresses configured. I think that would be best handled by a probe that prevents the router being included in the service unless it has been through initial configuration.

Understanding the cause of the memory growth in the console is also important. 

I would like to at least have the option of running the ragent and console colocated (I hope indeed to be able to run them in the same process). It may not be ideal in every case, but it reduces the footprint and perceive complexity in some cases. (In the brokered address space there is a single 'agent' that combines the roles of the console and the equivalent of the ragent).

**Comment by lulf** [comment] 2017-11-01 14:48
> Addresses being absent intermittently which led to anycast being used instead of multicast (as defined in our Addresses).

@calohmn As for this, I think we want to enable a configuration in the router that rejects clients that attaches to these unknown addresses. The reason its not enabled yet is that it doesn't work with the mqtt addresses.

**Comment by calohmn** [comment] 2017-11-01 15:46
@lulf You are referring to the "defaultDistribution: forbidden" setting from [DISPATCH-803](https://issues.apache.org/jira/browse/DISPATCH-803), right? Yes, that would help.

**Comment by lulf** [comment] 2017-11-23 11:31
@calohmn #561 adds support for DISPATCH-803, so 0.16.0 should have that fix. Release will probably be in a couple of weeks time.
