### ISSUE TITLE
Problem "watching" for resources

### ISSUE THREAD

**Issue by ctron** [EnMasseProject/enmasse#2103] opened 2018-12-11 10:21 UTC
**Describe the bug**

I think there is something wrong with the implementation of "watch". The `oc` client fails with an error message, while the go implementation continuously emits events and fails at the same time.

**To Reproduce**
1. Execute `oc get addressspace -w`

Results in:
~~~
➜  enmasse git:(feature/iot) ✗ oc get -w addressspace
NAME      AGE
default   7d
foo3x     17h
E1211 11:19:06.922714   22569 streamwatcher.go:109] Unable to decode an event from the watch stream: no kind "AddressSpaceList" is registered for version "enmasse.io/v1alpha1" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:57"
~~~

**Expected behavior**
 
Not to fail, and properly watch for changes.

**Comment by lulf** [comment] 2018-12-11 10:35
There is no implementation of watch. The error comes from the fact that oc get -w will try to use watches anyway even if the apiservice specifically does not specify support for the 'watch' operation.

**Comment by lulf** [comment] 2018-12-11 10:35
I think this is a duplicate of #1280

**Comment by ctron** [comment] 2018-12-11 13:52
Ok, that may be then. Based on the error reported by `oc` I assumed that watch was implemented, at least in a "namespaced" version.

**Comment by k-wall** [comment] 2019-06-20 09:34
Closing as duplicate

**Closed by k-wall** 2019-06-20 09:34 UTC
