### ISSUE TITLE
[Console] Purge and Suspend buttons not working

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#2265] opened 2019-01-28 13:07 UTC
**Describe the bug**
Sorry if this is a duplicate issue, did a quick search through existing issues and could only find #330  with any mention of this. 
In the console, the suspend and purge buttons seem permanently greyed out and not available/working for the end user.

**To Reproduce**
1. create a queue in console
2. send 100 messages to the queue
3. select the radio button for the address ( left side of the address name )  
4. open the menu "three dots" next to the delete button
5. attempt to purge the queue ( not available ),  or suspend the queue ( not available ) ..when clicked the words go white and not visible, then the little menu closes and nothing happens

**Expected behavior**
addresses should be either purged or suspended, or these options should be removed until the functionality is implemented

**Screenshots**
![image](https://user-images.githubusercontent.com/32485509/51838199-ebd62780-2305-11e9-9d68-ff2c6db8b305.png)

**Comment by k-wall** [comment] 2019-06-20 11:08
Duplicate of #330

**Closed by k-wall** 2019-06-20 11:08 UTC
Labels: console
