### ISSUE TITLE
Behaviour of agent and standard-controller on qdrouter restarts and many addresses

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1131] opened 2018-04-05 08:23 UTC
I've done a test with roughly 10k addresses - half brokered, half standard-anycast, using 1 qdrouter and 1 broker instance.

After all addresses were ready, I killed the qdrouter instance.

There are now 2 possible outcomes of such a test, depending on timing:

**1. Standard Controller doesn't notice the router addresses being gone**
In this case, the agent re-creates the qdrouter addresses while the StandardController is doing its 30s waiting interval in between checks (possibly with one check interrupted like this: `Error requesting router status from qdrouterd-65c79fc64c-qq2x4. Ignoring`).

_In this case, the situation resolves itself quite seamlessly - after 25s all is back to normal._
Here's log output from the agent:
````
2018-04-05T06:44:45.012Z agent info probe request: /probe
2018-04-05T06:44:50.204Z agent info probe request: /probe
 [qdrouter pod killed at 06:45:00]
2018-04-05T06:45:00.862Z agent info [Router.qdrouterd-65c79fc64c-qq2x4] aborting pending requests: disconnected
2018-04-05T06:45:00.862Z agent info router Router.qdrouterd-65c79fc64c-qq2x4 disconnected
2018-04-05T06:45:01.877Z agent info Router connected from Router.qdrouterd-65c79fc64c-npjlz
2018-04-05T06:45:01.884Z agent info [Router.qdrouterd-65c79fc64c-npjlz] router ready
2018-04-05T06:45:01.925Z agent info Router.qdrouterd-65c79fc64c-npjlz not ready for connectivity check: false false
2018-04-05T06:45:01.925Z agent info Router.qdrouterd-65c79fc64c-npjlz not ready for connectivity check: false true
2018-04-05T06:45:01.951Z agent info [Router.qdrouterd-65c79fc64c-npjlz] defining address event/BCX18
2018-04-05T06:45:01.952Z agent info [Router.qdrouterd-65c79fc64c-npjlz] defining in autolink for event/BCX18
2018-04-05T06:45:01.952Z agent info [Router.qdrouterd-65c79fc64c-npjlz] defining out autolink for event/BCX18
 [all addresses get re-defined in the qdrouter]
2018-04-05T06:45:03.316Z agent info [Router.qdrouterd-65c79fc64c-npjlz] defining address telemetry/test3_9
2018-04-05T06:45:03.316Z agent info [Router.qdrouterd-65c79fc64c-npjlz] updating addresses...
2018-04-05T06:45:15.012Z agent info probe request: /probe
2018-04-05T06:45:20.204Z agent info probe request: /probe
2018-04-05T06:45:45.012Z agent info probe request: /probe
````
Adding addresses in new Qdrouter "qdrouterd-65c79fc64c-npjlz" looks done at 6:45:23 - last entry:
````
2018-04-05 06:45:23.760802 +0000 AGENT (warning) The 'dir' attribute of autoLink has been deprecated. Use 'direction' instead
2018-04-05 06:45:23.760924 +0000 ROUTER_CORE (info) Auto Link Activated 'autoLinkOutevent/test3_9' on container broker-0
````

Log excerpt from the StandardController: 
[standardController_noConfigMapUpdates.txt](https://github.com/EnMasseProject/enmasse/files/1878964/standardController_noConfigMapUpdates.txt)

.

**2. Standard Controller updates all 10k ConfigMaps with unready state and then again with ready state**

Here the StandardController is busy for 10min, causing also the load of the K8s APIServer to go up to 3 with 60k requests (2xGET, 1xPUT per address for setting isReady=false, then the same for setting isReady=true). StandardController log excerpt:
````
2018-04-04 14:54:35.033 [Thread-4] INFO  AddressController:155 - onUpdate: done; total: 5591 ms, resolvedPlan: 2 ms, calculatedUsage: 4 ms, checkedQuota: 0 ms, listClusters: 544 ms, provisionResources: 0 ms, checkStatuses: 5032 ms, deprovisionUnused: 5 ms, replaceAddresses: 1 ms, gcTerminating: 0 ms
 [at 14:55 qdrouterd pod was deleted]
2018-04-04 14:55:54.815 [Thread-4] INFO  AddressController:155 - onUpdate: done; total: 49780 ms, resolvedPlan: 2 ms, calculatedUsage: 7 ms, checkedQuota: 0 ms, listClusters: 681 ms, provisionResources: 0 ms, checkStatuses: 601 ms, deprovisionUnused: 4 ms, replaceAddresses: 48480 ms, gcTerminating: 1 ms
..
2018-04-04 15:03:20.387 [Thread-4] INFO  AddressController:155 - onUpdate: done; total: 111772 ms, resolvedPlan: 6 ms, calculatedUsage: 14 ms, checkedQuota: 0 ms, listClusters: 582 ms, provisionResources: 0 ms, checkStatuses: 14059 ms, deprovisionUnused: 4 ms, replaceAddresses: 97103 ms, gcTerminating: 1 ms
..
2018-04-04 15:04:41.562 [Thread-4] INFO  AddressController:155 - onUpdate: done; total: 81174 ms, resolvedPlan: 4 ms, calculatedUsage: 5 ms, checkedQuota: 0 ms, listClusters: 679 ms, provisionResources: 0 ms, checkStatuses: 5359 ms, deprovisionUnused: 4 ms, replaceAddresses: 75118 ms, gcTerminating: 1 ms
2018-04-04 15:04:47.044 [Thread-4] INFO  AddressController:155 - onUpdate: done; total: 5481 ms, resolvedPlan: 2 ms, calculatedUsage: 3 ms, checkedQuota: 0 ms, listClusters: 555 ms, provisionResources: 0 ms, checkStatuses: 4914 ms, deprovisionUnused: 4 ms, replaceAddresses: 0 ms, gcTerminating: 0 ms
````
The agent pod also has to work heavily to process these updates. It gets restarted a few times because the liveness probes (periodSeconds=30, timeoutSeconds=5) don't get handled while address updates are handled:
````
2018-04-04T14:54:32.058Z agent info probe request: /probe
 [at 14:55 qdrouterd pod was deleted]
2018-04-04T14:55:01.132Z agent info [Router.qdrouterd-65c79fc64c-hwvp7] aborting pending requests: disconnected
2018-04-04T14:55:01.132Z agent info router Router.qdrouterd-65c79fc64c-hwvp7 disconnected
2018-04-04T14:55:02.001Z agent info probe request: /probe
2018-04-04T14:55:02.034Z agent info probe request: /probe
[broker-0] failed to retrieve addresses: ["AMQ119067: Cannot find resource with name queue.event/test1_1097"]
2018-04-04T14:55:02.070Z agent error [broker-0] failed to retrieve addresses: ["AMQ119067: Cannot find resource with name queue.event/test1_1097"]
[broker-0] failed to retrieve addresses: ["AMQ119067: Cannot find resource with name address.event/test1_22"]
2018-04-04T14:55:05.775Z agent error [broker-0] failed to retrieve addresses: ["AMQ119067: Cannot find resource with name address.event/test1_22"]
2018-04-04T14:55:06.474Z agent info addresses_defined: modified ["event/SMOKE_TEST_TENANT"]
2018-04-04T14:55:06.846Z agent info addresses_defined: modified event/test1_500, event/test1_501, event/test1_502, event/test1_503, event/test1_504 and 29 more
2018-04-04T14:55:11.021Z agent info addresses_defined: modified event/test1_522, event/test1_523, event/test1_524, event/test1_525, event/test1_528 and 336 more
2018-04-04T14:55:49.694Z agent info [broker-0] connection error: {"type":"error#1d","condition":"amqp:resource-limit-exceeded","description":"local-idle-timeout expired"}
2018-04-04T14:55:49.711Z agent info [broker-0] connection closed
2018-04-04T14:55:49.711Z agent info broker disconnected: broker-0
[broker-0] failed to retrieve addresses: undefined
2018-04-04T14:55:49.737Z agent error [broker-0] failed to retrieve addresses: undefined
2018-04-04T14:55:49.848Z agent info addresses_defined: modified event/PERF_TEST_TENANT, event/test1_700, event/test1_701, event/test1_702, event/test1_703 and 337 more
2018-04-04T14:56:26.822Z agent info probe request: /probe
2018-04-04T14:56:26.825Z agent info probe request: /probe
2018-04-04T14:56:26.933Z agent info addresses_defined: modified event/test1_2000, event/test1_2001, event/test1_2002, event/test1_2003, event/test1_2004 and 336 more
2018-04-04T14:57:04.140Z agent info probe request: /probe
2018-04-04T14:57:04.143Z agent info probe request: /probe
2018-04-04T14:57:04.248Z agent info addresses_defined: modified event/test1_2050, event/test1_2051, event/test1_2052, event/test1_2053, event/test1_2054 and 337 more
[pod gets killed here because of failing livenessProbes]
````
Next agent log:
````
2018-04-04T14:57:07.799Z agent info GET /oapi/v1/namespaces/hono/routes/messaging => 404 
2018-04-04T14:57:07.804Z agent info could not retrieve messaging route hostname
2018-04-04T14:57:07.823Z agent info Router agent listening on 55671
2018-04-04T14:57:08.701Z agent info GET /api/v1/namespaces/hono/configmaps?labelSelector=type%3Daddress-config => 200 
2018-04-04T14:57:08.988Z agent info addresses_defined: undefined
2018-04-04T14:57:09.121Z agent info addresses_ready: undefined
2018-04-04T14:57:09.121Z agent info triggering address configuration check
2018-04-04T14:57:09.134Z agent info address configuration check triggered
2018-04-04T14:57:09.147Z agent info GET /api/v1/watch/namespaces/hono/configmaps?labelSelector=type%3Daddress-config => 200 
2018-04-04T14:57:12.311Z agent info addresses_defined: modified telemetry/test2_1642, telemetry/test2_1643, telemetry/test2_1644, telemetry/test2_1645, telemetry/test2_1647 and 32 more
2018-04-04T14:57:25.321Z agent info addresses_defined: modified telemetry/IOT_ACADEMY, telemetry/test1_900, telemetry/test1_901, telemetry/test1_902, telemetry/test1_903 and 83 more
2018-04-04T14:58:00.356Z agent info addresses_defined: modified telemetry/test1_765, telemetry/test1_766, telemetry/test1_767, telemetry/test1_768, telemetry/test1_769 and 198 more
[pod again killed]
````

This all leads me to question, whether the ready state of addresses really should be persisted in the ConfigMap. Also whether there should be some kind of synchronizing the actions of agent and StandardController - or consolidating address provisioning and broker/qdrouter scaling into one component.

**Comment by grs** [comment] 2018-04-05 08:29
One further comment on agent, the chattiness of broker management is currently also increasing the load of simple address checking. I can reduce this significantly and will work on it today.

**Comment by lulf** [comment] 2018-04-05 08:37
>  all leads me to question, whether the ready state of addresses really should be persisted in the ConfigMap

I think the main issue here is that we have to send the whole payload in order to update/retrieve a single field. If we used custom resource instead, we could support subresources as the way of updating the status. This is how pods are updated by kubernetes for instance, the controllers only write to the 'status' part of the pod definition with as in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#-strong-status-operations-strong--67

In general, there are a lot of ways to optimize the API usage by looking at https://kubernetes.io/docs/reference/api-concepts/

**Comment by grs** [comment] 2018-04-05 09:10
I think ideally when a router (re)starts, it should not be considered ready (and therefore not actually used to handle client connections) until it is synced with the addresses currently defined. While it reaches this state, the status of all the addresses would ideally not need to be changed. Need to think a bit more about how that might be implemented.

**Comment by lulf** [comment] 2018-04-05 10:02
Wouldn't that be the reason for having 2 routers then? If one goes down, the status check will pass because there is another router that is up and configured. On master, the status check will only consider routers that have passed the readiness check when looking at status.

**Comment by grs** [comment] 2018-04-05 10:08
The readiness check on the router right now is simply that the router accepts connections. My assumption was that even if you had two routers, when one of them is restarted it will become ready before it is fully configured (especially where there are a lot of addresses), and if the standard-controller notices this it will then proceed to updating the status on all those addresses.

However as the status check is only done on ready routers, I think we could improve things just be defining an executable as the readiness probe, which would check that the router has all the defined addresses configured.

**Comment by lulf** [comment] 2018-04-05 10:14
I don't think that will work though. If you create a new address, you don't want the router readiness check to fail and prevent new connections to the other addresses?

**Comment by grs** [comment] 2018-04-05 10:26
> If you create a new address, you don't want the router readiness check to fail and prevent new connections for existing addresses?

Ideally not. (I think in real use, adding new addresses would be fairly infrequent. Also if you added a whole batch of new addresses, then preventing new connections until the routers have caught up *might* not be a bad thing).

We could however define a special address that is created to indicate that the initial provisioning has completed, and use the presence of that address as the readiness test. That also makes the check much quicker - with the default distribution being undefined, it only requires the probe to verify it can attach to the marker address.

**Comment by lulf** [comment] 2018-04-05 11:03
I guess we need to make sure that existing connections are still alive even if the probe fails then. If so, then I agree it is perhaps not critical. However, if in the future we end up using the router vhost feature for multiple tenants, then we can't disrupt other tenants use of the router based on new addresses created for a different tenant.

At present, the standard-controller logic assumes all addresses are not ready before running the readiness checks, which would have to change.

Conceptually I have some issues with an address being marked as ready but that it is in fact not ready due to the router restarting. If we can make updating the readiness more light-weight, wouldn't that be a better approach? Or are there other reasons than the frequent update of the status for changing the router readiness check?

**Comment by lulf** [comment] 2018-04-05 11:13
I agree with the general notion that a router should not be part of the service endpoints before it has received the initial configuration though, and I think the special address is a good approach. Ideally, and I think I've proposed a feature for the router in the past where you would be able to 'activate' the router once you know you have configured it.

**Comment by grs** [comment] 2018-04-05 13:16
Actually you could even just avoid creating the listeners until the initial configuration is complete. That would automatically mean it is not available until then. (i.e. create the listeners dynamically rather than statically as we do now)

**Comment by lulf** [comment] 2018-04-05 13:32
> Actually you could even just avoid creating the listeners until the initial configuration is complete. That would automatically mean it is not available until then. (i.e. create the listeners dynamically rather than statically as we do now)

That seems like a good solution to me. Having a look at the standard-controller, my earlier comment around "standard-controller logic assumes all addresses are not ready before running the readiness checks" is wrong. It assumes everything is up and running, and then checks the status of all ready routers. Therefore I think having the router agent create the listeners on initial configuration should fix the API usage as well.

**Comment by calohmn** [comment] 2018-04-05 16:53
So, to summarize: while the agent is still busy doing the initial address provisioning in the qdrouter, the standard-controller will invoke `AddressController.checkStatuses()`, will set isReady=true for the addresses and will then keep that state because the actual router-address check is skipped because it cannot yet connect to the router (because agent hasn't added the listener yet).

> Conceptually I have some issues with an address being marked as ready but that it is in fact not ready due to the router restarting. If we can make updating the readiness more light-weight, wouldn't that be a better approach? Or are there other reasons than the frequent update of the status for changing the router readiness check?

Yes, marking the addresses ready although the router is not ready yet doesn't seem so good. Doing the ConfigMap updates with isReady=false on the other hand seems rather too expensive (at least at the moment). 
But on the other hand, as long as the standardController doesn't detect the qdrouter going absent, the isReady-flag is only a recent snapshot that doesn't necessarily represent the current state anyway. So, the current behaviour of keeping isReady=true during restarts might not be too bad.
(And I guess this all would only be relevant if there is only one qdrouter instance anyway.)

And after having made the change from Address ConfigMaps to Address CustomResourceDefinitions (CRDs), updates could be done via the "status" subresource as mentioned above (although this really calls for a (currently non-existing) bulk update feature) and also the standardController could watch for qdrouter restarts.
(I guess it would also make sense to set isReady=false on the AddressSpace while the only existing qdrouter is restarting.)


A further question: Have there been thoughts on moving all address provisioning/checking and router/broker scaling functionality into one component? I mean, there seems to be some overlap in agent and StandardController as of now concerning address checks in router and broker.

**Comment by lulf** [comment] 2018-04-05 17:45
> So, to summarize: while the agent is still busy doing the initial address provisioning in the qdrouter, the standard-controller will invoke AddressController.checkStatuses(), will set isReady=true for the addresses and will then keep that state because the actual router-address check is skipped because it cannot yet connect to the router (because agent hasn't added the listener yet).

Yes, I think that sums it up well!

> A further question: Have there been thoughts on moving all address provisioning/checking and router/broker scaling functionality into one component? I mean, there seems to be some overlap in agent and StandardController as of now concerning address checks in router and broker.

We did discuss merging standard-controller and agent. The motivation is that we could reduce the number of components running in the system. Another point was that the node runtime seemed to require less resources at the time. From your experiments, I think that the latter argument becomes somewhat void since I think the node process requires just as much memory as the java parts when you start doing more stuff.

When adding support for plans, we decided to keep the standard-controller and agent separate for now, with the goal of moving the status checks in the standard-controller over to the agent. The standard-controller would then be responsible for provisioning routers and brokers (or any component required by the plans) and 'assigning' addresses to brokers, whereas the agent would be responsible for configuring the routers and brokers based on that state and update the status. For now, porting the status checks to the agent has not been prioritized.

There is also another question if we should merge both components. One is written in javascript and the other in java. My personal preference based on operating and debugging so far is java since I think we get some more visibility into the JVM than we do into the node process, and it allows for utilizing more than 1 cpu core. On the other hand, having the console server and client share code is also convenient.

We could in theory have a look at running both agent and standard-controller on the same runtime using vertx, but that would likely require some changes to the agent to ensure it runs well there. We could also port the standard-controller code to javascript, but I'm not a big fan of javascript TBH :)

**Comment by grs** [comment] 2018-04-05 17:56
> So, to summarize: while the agent is still busy doing the initial address provisioning in the qdrouter, the standard-controller will invoke AddressController.checkStatuses(), will set isReady=true for the addresses and will then keep that state because the actual router-address check is skipped because it cannot yet connect to the router (because agent hasn't added the listener yet).

Probably saying the same thing, but I believe the addresses won't be marked as isReady=true until at least one router has been confirmed to have that address configured. However if that router then restarts, and is being reprovisioned, if we only create the external listeners after the current addresses are configured, then the router will not show up in the set that the standard-controller is checking until it has caught up, so the isReady won't be set back to false.

A new address created at the point when the single router is down (or all routers are down) would not become ready until at least one router is up and correctly provisioned.

**Comment by grs** [comment] 2018-04-05 18:15
> Another point was that the node runtime seemed to require less resources at the time. From your experiments, I think that the latter argument becomes somewhat void since I think the node process requires just as much memory as the java parts when you start doing more stuff.

I think the evidence is still inconclusive on that point. The memory use is high at present because the agent is doing a lot of unnecessary stuff (39k request/responses to get stats for 3k queues!). Once this is fixed I hope the picture will change.

That said I think the reason for the current choices was always really just developer preference rather any proper comparative analysis.

> We could in theory have a look at running both agent and standard-controller on the same runtime using vertx

I think that would be the worst of both worlds!

> We could also port the standard-controller code to javascript, but I'm not a big fan of javascript TBH :)

We could also port the agent/console-server code to java, but I'm not a big fan of java TBH :)

**Comment by lulf** [comment] 2019-10-15 06:53
I think this behavior has improved now. Tracking the agent/standard-controller work in #3313

**Closed by lulf** 2019-10-15 06:53 UTC
