### ISSUE TITLE
No messages delivered on brokered addresses anymore

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1255] opened 2018-05-23 09:01 UTC
We have done some performance tests, first by sending messages on an anycast address and then on a brokered address.

During the test with the brokered address, we got some errors in the broker that the corresponding queue is full:
> 2018-05-22 14:37:57,324 WARN  [org.apache.activemq.artemis.protocol.amqp.proton.ProtonServerReceiverContext] AMQ119102: Address "event/LOAD_TEST_TENANT" is full.: ActiveMQAddressFullException[errorType=ADDRESS_FULL message=AMQ119102: Address "event/LOAD_TEST_TENANT" is full.]

In the router stats, these errors correspond to rejected messages.

Now the issue:
Later messages on the brokered address don't get delivered anymore - even when the size of the Artemis address is zero again. On the sender side in Hono we get a timeout. Looking at the router stats, these new messages increment the "undelivered" counter.
Stats before:
````
Router Links
  type      dir  conn id  id     peer  class   addr                           phs  cap  undel  unsett  del    presett  psdrop  acc    rej  rel  mod  admin    oper
  ==================================================================================================================================================================
  endpoint  in   1        6                                                        250  0      0       26     0        0       26     0    0    0    enabled  up
  endpoint  out  1        7            local   temp.Zc9fZGY5eu8QBMf                250  0      0       26     26       0       0      0    0    0    enabled  up
  endpoint  out  15       30           mobile  event/LOAD_TEST_TENANT         0    250  0      0       2623   0        0       2623   0    0    0    enabled  up
  endpoint  out  5        31           mobile  telemetry/HEALTH_CHECK_TENANT  0    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  out  6        32           mobile  event/HEALTH_CHECK_TENANT      0    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  in   95       83                                                       250  0      0       34728  0        0       34728  0    0    0    enabled  up
  endpoint  out  95       84           local   temp.KsDwq5hpjW5bInE                250  0      0       34728  34728    0       0      0    0    0    enabled  up
  endpoint  in   169      128          mobile  event/HEALTH_CHECK_TENANT      1    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  out  169      129          mobile  event/HEALTH_CHECK_TENANT      0    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  in   170      130          mobile  event/HUB_TEAM_TENANT          1    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  out  170      131          mobile  event/HUB_TEAM_TENANT          0    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  in   171      132          mobile  event/LOAD_TEST_TENANT         1    250  0      0       15653  0        0       15653  0    0    0    enabled  up
  endpoint  out  171      133          mobile  event/LOAD_TEST_TENANT         0    250  200    0       15900  0        0       15653  247  0    0    enabled  up
  endpoint  in   172      134          mobile  event/SMOKE_TEST_TENANT        1    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  out  172      135          mobile  event/SMOKE_TEST_TENANT        0    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  in   173      136          mobile  event/PERF_TEST_TENANT         1    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  out  173      137          mobile  event/PERF_TEST_TENANT         0    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  in   33081    15620        mobile  $management                    0    250  0      0       1      0        0       1      0    0    0    enabled  up
  endpoint  out  33081    15621        local   temp.GeDiBp2KLr7VhZ+                250  0      0       0      0        0       0      0    0    0    enabled  up
````
Then, after having sent 7 messages on `event/LOAD_TEST_TENANT`:
````
Router Links
  type      dir  conn id  id     peer  class   addr                       phs  cap  undel  unsett  del    presett  psdrop  acc    rej  rel  mod  admin    oper
  ==============================================================================================================================================================
  endpoint  in   1        6                                                    250  0      0       26     0        0       26     0    0    0    enabled  up
  endpoint  out  1        7            local   temp.Zc9fZGY5eu8QBMf            250  0      0       26     26       0       0      0    0    0    enabled  up
  endpoint  in   95       83                                                   250  0      0       36648  0        0       36648  0    0    0    enabled  up
  endpoint  out  95       84           local   temp.KsDwq5hpjW5bInE            250  0      0       36648  36648    0       0      0    0    0    enabled  up
  endpoint  in   169      128          mobile  event/HEALTH_CHECK_TENANT  1    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  out  169      129          mobile  event/HEALTH_CHECK_TENANT  0    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  in   170      130          mobile  event/HUB_TEAM_TENANT      1    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  out  170      131          mobile  event/HUB_TEAM_TENANT      0    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  in   171      132          mobile  event/LOAD_TEST_TENANT     1    250  0      0       15653  0        0       15653  0    0    0    enabled  up
  endpoint  out  171      133          mobile  event/LOAD_TEST_TENANT     0    250  207    0       15900  0        0       15653  247  0    0    enabled  up
  endpoint  in   172      134          mobile  event/SMOKE_TEST_TENANT    1    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  out  172      135          mobile  event/SMOKE_TEST_TENANT    0    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  in   173      136          mobile  event/PERF_TEST_TENANT     1    250  0      0       0      0        0       0      0    0    0    enabled  up
  endpoint  out  173      137          mobile  event/PERF_TEST_TENANT     0    250  0      0       5      0        0       5      0    0    0    enabled  up
  endpoint  in   11       16383        mobile  event/PERF_TEST_TENANT     0    50   0      0       1      0        0       1      0    0    0    enabled  up
  endpoint  in   35814    16488        mobile  $management                0    250  0      0       1      0        0       1      0    0    0    enabled  up
  endpoint  out  35814    16489        local   temp.YPqAZFlsiDm7UT_            250  0      0       0      0        0       0      0    0    0    enabled  up
````
Restarting either router or broker resolves the issue.

The test is reproducible in our environment. 
Router and broker are from EnMasse 0.19.

We have assembled some log output with `PN_TRACE_FRM=1`:
- Test resulting in undelivered messages (address is `event/LOAD_TEST_TENANT`): 
[ErrorCase_LOAD_TEST_TENANT_Router.log](https://github.com/EnMasseProject/enmasse/files/2030265/ErrorCase_LOAD_TEST_TENANT_Router.log)
[ErrorCase_LOAD_TEST_TENANT_Broker.log](https://github.com/EnMasseProject/enmasse/files/2030266/ErrorCase_LOAD_TEST_TENANT_Broker.log)
- for comparison: Test with messages that get delivered (address is `event/PERF_TEST_TENANT`):
[OKCase_PERF_TEST_TENANT_Router.log](https://github.com/EnMasseProject/enmasse/files/2030269/OKCase_PERF_TEST_TENANT_Router.log)
[OKCase_PERF_TEST_TENANT_Broker.log](https://github.com/EnMasseProject/enmasse/files/2030270/OKCase_PERF_TEST_TENANT_Broker.log)

**Comment by calohmn** [comment] 2018-05-23 09:33
Concerning the above logs:
In the error case, the router log only contains one incoming transfer:
````
[0x7efdb8172f20]:0 <- @transfer(20) [handle=0, delivery-id=7954, delivery-tag=b"2", message-format=0] (360) "\x00Sr\xc1j\x06\xa3\x09tenant_id\xa1\x10LOAD_TEST_TENANT\xa3\x09device_id\xa1\x0emy-test-device\xa3\x08resource\xa1%event/LOAD_TEST_TENANT/my-test-device\x00Ss\xd0\x00\x00\x00E\x00\x00\x00\x07\xa1\x11EventSenderImpl-6@\xa1\x16event/LOAD_TEST_TENANT@@@\xa3\x10application/json\x00St\xc1\x94\x08\xa1\x0corig_adapter\xa1\x09hono-http\xa1\x09device_id\xa1\x0emy-test-device\xa1\x0corig_address\xa1&/event/LOAD_TEST_TENANT/my-test-device\xa1\x15JMS_AMQP_CONTENT_TYPE\xa1\x10application/json\x00Su\xa0\x0e{"Foo": "Bar"}"
````
In the OK case, there is the following log output - with outgoing transfer:
````
[0x7efdb81abcb0]:0 <- @attach(18) [name="auto-4", handle=0, role=false, snd-settle-mode=0, rcv-settle-mode=0, source=@source(40) [durable=0, expiry-policy=:"session-end", timeout=0, dynamic=false, outcomes=@PN_SYMBOL[:"amqp:accepted:list", :"amqp:rejected:list", :"amqp:released:list", :"amqp:modified:list"]], target=@target(41) [address="event/PERF_TEST_TENANT"], incomplete-unsettled=false, initial-delivery-count=0]
[0x7efdb81abcb0]:0 -> @attach(18) [name="auto-4", handle=0, role=true, snd-settle-mode=2, rcv-settle-mode=0, source=@source(40) [durable=0, timeout=0, dynamic=false, outcomes=@PN_SYMBOL[:"amqp:accepted:list", :"amqp:rejected:list", :"amqp:released:list", :"amqp:modified:list"]], target=@target(41) [address="event/PERF_TEST_TENANT", durable=0, timeout=0, dynamic=false], initial-delivery-count=0, max-message-size=0]
[0x7efdb81abcb0]:0 -> @flow(19) [next-incoming-id=8161, incoming-window=2147483647, next-outgoing-id=0, outgoing-window=2147483647, handle=0, delivery-count=0, link-credit=50, drain=false]
[0x7efdb81abcb0]:0 <- @transfer(20) [handle=0, delivery-id=8160, delivery-tag=b"1", message-format=0] (360) "\x00Sr\xc1j\x06\xa3\x09tenant_id\xa1\x10PERF_TEST_TENANT\xa3\x09device_id\xa1\x0emy-test-device\xa3\x08resource\xa1%event/PERF_TEST_TENANT/my-test-device\x00Ss\xd0\x00\x00\x00E\x00\x00\x00\x07\xa1\x11EventSenderImpl-8@\xa1\x16event/PERF_TEST_TENANT@@@\xa3\x10application/json\x00St\xc1\x94\x08\xa1\x0corig_adapter\xa1\x09hono-http\xa1\x09device_id\xa1\x0emy-test-device\xa1\x0corig_address\xa1&/event/PERF_TEST_TENANT/my-test-device\xa1\x15JMS_AMQP_CONTENT_TYPE\xa1\x10application/json\x00Su\xa0\x0e{"Foo": "Bar"}"
[0xdd0c40]:1 -> @transfer(20) [handle=0, delivery-id=4, delivery-tag=b"\xba\x9b\x13\x00\x00\x00\x00\x00", message-format=0, settled=false, more=false, resume=false, aborted=false, batchable=false] (366) "\x00Sr\xd1\x00\x00\x00m\x00\x00\x00\x06\xa3\x09tenant_id\xa1\x10PERF_TEST_TENANT\xa3\x09device_id\xa1\x0emy-test-device\xa3\x08resource\xa1%event/PERF_TEST_TENANT/my-test-device\x00Ss\xd0\x00\x00\x00E\x00\x00\x00\x07\xa1\x11EventSenderImpl-8@\xa1\x16event/PERF_TEST_TENANT@@@\xa3\x10application/json\x00St\xc1\x94\x08\xa1\x0corig_adapter\xa1\x09hono-http\xa1\x09device_id\xa1\x0emy-test-device\xa1\x0corig_address\xa1&/event/PERF_TEST_TENANT/my-test-device\xa1\x15JMS_AMQP_CONTENT_TYPE\xa1\x10application/json\x00Su\xa0\x0e{"Foo": "Bar"}"
[0xdd0c40]:1 <- @disposition(21) [role=true, first=4, last=4, settled=true, state=@accepted(36) []]
[0x7efdb81abcb0]:0 -> @flow(19) [next-incoming-id=8162, incoming-window=2147483647, next-outgoing-id=0, outgoing-window=2147483647, handle=0, delivery-count=1, link-credit=50, drain=false]
[0x7efdb81abcb0]:0 -> @disposition(21) [role=true, first=8160, last=8160, settled=true, state=@accepted(36) []]
````

**Comment by lulf** [comment] 2018-05-23 09:52
@calohmn It would be interesting to know more about the state of the broker and the connector services. In 0.19 , there is one connector service per queue, so if you go to the broker console you should expected to see one entry for the event/LOAD_TEST_TENANT address. On 0.20.0, we're moving back to 1 connector service in total, so could be interesting to see if you can reproduce this issue with the latest 0.20.0 rc

**Comment by grs** [comment] 2018-05-23 10:01
Is there any more of the router log?

**Comment by calohmn** [comment] 2018-05-23 10:39
@grs I don't have the complete log from the test run with `PN_TRACE_FRM=1`. A previous test run without the flag showed no interesting output: 
[qdrouterd-7f7f694d74-t79gm_router_20180522_164646.log.zip](https://github.com/EnMasseProject/enmasse/files/2030637/qdrouterd-7f7f694d74-t79gm_router_20180522_164646.log.zip)

@lulf Yes, we'll repeat the test with 0.20.0 rc.

**Comment by grs** [comment] 2018-05-23 10:51
@calohmn can you still get qdmanage output? for a query of autolinks? qdmanage QUERY --type=autoLink

**Comment by calohmn** [comment] 2018-05-23 13:04
We have done the load test again with a build that includes the router update from PR #1227:
It also showed the error.

**Comment by grs** [comment] 2018-05-25 08:48
@calohmn yes, debug logs would help I think if we can reproduce with them on. SERVER should be fine.

Fyi, to update logs on the fly the following should work:

```qdmanage update --type=log --name=log/SERVER --stdin```

Then type in on the console:

```{"enable":"trace+"}```

Ctrl-D and it should turn that on (works for me ;-)

**Comment by calohmn** [comment] 2018-05-25 13:33
@grs Thanks, that helped. I've activated it on the DEFAULT module instead of SERVER (SERVER didn't seem enough).

Log output for the FAIL ("message undelivered") case ("LOAD_TEST_TENANT"):
````
2018-05-25 13:04:23.871966 +0000 POLICY (trace) ALLOW AMQP Attach sender link 'event/LOAD_TEST_TENANT' for user '', rhost '100.106.0.7', vhost 'hono-internal' based on link target name
2018-05-25 13:04:23.872029 +0000 ROUTER_CORE (trace) Core action 'link_first_attach'
2018-05-25 13:04:23.872052 +0000 DEFAULT (trace) Parse tree search for 'event/LOAD_TEST_TENANT'
2018-05-25 13:04:23.872060 +0000 DEFAULT (trace) Parse tree match not found
2018-05-25 13:04:23.872068 +0000 DEFAULT (trace) Parse tree search for 'event/LOAD_TEST_TENANT'
2018-05-25 13:04:23.894979 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2e011ded0 rc:1 qdr_link_deliver - newly created delivery, add to action list
2018-05-25 13:04:23.895005 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2e011ded0 rc:2 qdr_link_deliver - protect returned value
2018-05-25 13:04:23.895021 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2e011ded0 rc:3 referenced by a pn_delivery
2018-05-25 13:04:23.895032 +0000 ROUTER_CORE (debug) Delivery decref:    dlv:7fc2e011ded0 rc:2 release protection of return from deliver
2018-05-25 13:04:23.895053 +0000 ROUTER_CORE (trace) Core action 'link_deliver'
2018-05-25 13:04:23.895071 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2d82722d0 rc:1 qdr_delivery_link_peers_CT - linked to peer (1)
2018-05-25 13:04:23.895087 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2e011ded0 rc:3 qdr_delivery_link_peers_CT - linked to peer (2)
2018-05-25 13:04:23.895119 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2d82722d0 rc:2 qdr_forward_deliver_CT - add to undelivered list
2018-05-25 13:04:23.895134 +0000 ROUTER_CORE (debug) Delivery transfer:  dlv:7fc2e011ded0 qdr_link_forward_CT: action-list -> unsettled-list
````

Log output for the OK case ("PERF_TEST_TENANT"):
````
2018-05-25 13:08:38.773965 +0000 POLICY (trace) ALLOW AMQP Attach sender link 'event/PERF_TEST_TENANT' for user '', rhost '100.100.0.6', vhost 'hono-internal' based on link target name
2018-05-25 13:08:38.774331 +0000 ROUTER_CORE (trace) Core action 'link_first_attach'
2018-05-25 13:08:38.774418 +0000 DEFAULT (trace) Parse tree search for 'event/PERF_TEST_TENANT'
2018-05-25 13:08:38.774458 +0000 DEFAULT (trace) Parse tree match not found
2018-05-25 13:08:38.774496 +0000 DEFAULT (trace) Parse tree search for 'event/PERF_TEST_TENANT'
2018-05-25 13:08:38.798956 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2d84154d0 rc:1 qdr_link_deliver - newly created delivery, add to action list
2018-05-25 13:08:38.798986 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2d84154d0 rc:2 qdr_link_deliver - protect returned value
2018-05-25 13:08:38.799006 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2d84154d0 rc:3 referenced by a pn_delivery
2018-05-25 13:08:38.799015 +0000 ROUTER_CORE (trace) Core action 'link_deliver'
2018-05-25 13:08:38.799059 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2d8097d90 rc:1 qdr_delivery_link_peers_CT - linked to peer (1)
2018-05-25 13:08:38.799040 +0000 ROUTER_CORE (debug) Delivery decref:    dlv:7fc2d84154d0 rc:2 release protection of return from deliver
2018-05-25 13:08:38.799084 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2d84154d0 rc:3 qdr_delivery_link_peers_CT - linked to peer (2)
2018-05-25 13:08:38.799112 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2d8097d90 rc:2 qdr_forward_deliver_CT - add to undelivered list
2018-05-25 13:08:38.799126 +0000 ROUTER_CORE (debug) Delivery transfer:  dlv:7fc2d84154d0 qdr_link_forward_CT: action-list -> unsettled-list
2018-05-25 13:08:38.799187 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2d8097d90 rc:3 referenced by a pn_delivery
2018-05-25 13:08:38.799211 +0000 ROUTER_CORE (debug) Delivery transfer:  dlv:7fc2d8097d90 qdr_link_process_deliveries: undelivered-list -> unsettled-list
2018-05-25 13:08:38.799334 +0000 ROUTER_CORE (trace) Core action 'link_flow'
2018-05-25 13:08:38.800313 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2d8097d90 rc:4 qdr_delivery_update_disposition - add to action list
2018-05-25 13:08:38.800379 +0000 ROUTER_CORE (debug) Delivery decref:    dlv:7fc2d8097d90 rc:3 removed reference from pn_delivery
2018-05-25 13:08:38.800410 +0000 ROUTER_CORE (trace) Core action 'update_delivery'
2018-05-25 13:08:38.800455 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2d84f2590 rc:1 qdr_link_deliver - newly created delivery, add to action list
2018-05-25 13:08:38.800450 +0000 ROUTER_CORE (debug) Delivery decref_CT: dlv:7fc2d8097d90 rc:2 qdr_delivery_unlink_peers_CT - unlinked from peer (1)
2018-05-25 13:08:38.800484 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2d84f2590 rc:2 qdr_link_deliver - protect returned value
2018-05-25 13:08:38.800494 +0000 ROUTER_CORE (debug) Delivery decref_CT: dlv:7fc2d84154d0 rc:2 qdr_delivery_unlink_peers_CT - unlinked from peer (2)
2018-05-25 13:08:38.800515 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2d84154d0 rc:3 qdr_delivery_push_CT - add to updated list
2018-05-25 13:08:38.800531 +0000 ROUTER_CORE (debug) Delivery decref_CT: dlv:7fc2d8097d90 rc:1 qdr_update_delivery_CT - remove from action
2018-05-25 13:08:38.800497 +0000 ROUTER_CORE (debug) Delivery incref:    dlv:7fc2d84f2590 rc:3 referenced by a pn_delivery
2018-05-25 13:08:38.800577 +0000 ROUTER_CORE (debug) Delivery decref:    dlv:7fc2d84f2590 rc:2 release protection of return from deliver
2018-05-25 13:08:38.800552 +0000 ROUTER_CORE (debug) Delivery decref_CT: dlv:7fc2d8097d90 rc:0 qdr_update_delivery_CT - removed from unsettled (1)
2018-05-25 13:08:38.801188 +0000 ROUTER_CORE (debug) Delivery decref_CT: dlv:7fc2d84154d0 rc:2 qdr_update_delivery_CT - removed from unsettled (2)
2018-05-25 13:08:38.801204 +0000 ROUTER_CORE (trace) Core action 'link_deliver'
2018-05-25 13:08:38.801212 +0000 ROUTER_CORE (debug) Delivery transfer:  dlv:7fc2d84f2590 qdr_link_forward_CT: action-list -> undelivered-list
2018-05-25 13:08:38.801422 +0000 ROUTER_CORE (debug) Delivery decref:    dlv:7fc2d84154d0 rc:1 removed reference from pn_delivery
2018-05-25 13:08:38.801446 +0000 ROUTER_CORE (debug) Delivery decref:    dlv:7fc2d84154d0 rc:0 qdr_connection_process - remove from updated list
2018-05-25 13:08:38.801509 +0000 ROUTER_CORE (trace) Core action 'delete_delivery'
2018-05-25 13:08:38.850745 +0000 ROUTER_CORE (trace) Core action 'send_to'
2018-05-25 13:08:38.850804 +0000 ROUTER_HELLO (trace) SENT: HELLO(id=Router.qdrouterd-5bbd67fd6c-6mxnz pv=1 area=0 inst=1527246341 seen=[])
````
Here are logs and some stats: 
[logs_stats.zip](https://github.com/EnMasseProject/enmasse/files/2039499/logs_stats.zip)

**Comment by calohmn** [comment] 2018-05-29 14:51
We have done some more tests with EnMasse 0.20.0 together with router image from PR #1227:
As the `max_size_bytes` Artemis address setting is not effectively set to 100kB there anymore, we didn't get the "Address [..] is full" errors in the Artemis log. As a result we also saw no messages staying "undelivered" even after Artemis address size is zero again.

To again reproduce the Artemis "Address [..] is full" errors with that setup, we have set the `GLOBAL_MAX_SIZE` for Artemis to `100kB`. 
Indeed these errors showed up again and after some time, message senders got timeouts and messages were not delivered anymore.

This time we got the complete qpid logs: [logs_180529.zip](https://github.com/EnMasseProject/enmasse/files/2048675/logs_180529.zip)
qdstat/qdmanage output: [qdstat_qdmanage_180529.zip](https://github.com/EnMasseProject/enmasse/files/2048676/qdstat_qdmanage_180529.zip)
The error state started at some point before `2018-05-29 14:24`.

**Comment by grs** [comment] 2018-05-29 21:52
I can't see any interaction between the router and the broker in that latest router log. All the incoming messages seem to be management queries. Is this definitely the right router log?

The address in question is a queue (not a topic?) is that right? What should happen is that the messages delivered when the queue is full get a rejected disposition containing the error. However that should clear once the messages have been dequeued.

**Comment by grs** [comment] 2018-05-29 22:21
I did a quick test on master with 100kb global-max-size and I see expected behaviour. (i.e. messages rejected when full, but accepted again when queue is emptied).

**Comment by calohmn** [comment] 2018-05-30 12:33
> I can't see any interaction between the router and the broker in that latest router log. All the incoming messages seem to be management queries. Is this definitely the right router log?

yes, you can see the corresponding `transfer` operations by doing a `grep 'hono-mqtt' qdrouterd.log`:
````
2018-05-29 14:22:51.507067 +0000 SERVER (trace) [468]:0 -> @transfer(20) [handle=0, delivery-id=0, delivery-tag=b"6\x02\x00\x00\x00\x00\x00\x00", message-format=0] (907) "\x00Sr\xd1\x00\x00\x00w\x00\x00\x00\x06\xa3\x09tenant_id\xa1\x10LOAD_TEST_TENANT\xa3\x09device_id\xa1\x13loadTestClient-8004\xa3\x08resource\xa1*event/LOAD_TEST_TENANT/loadTestClient-8004\x00Ss\xd0\x00\x00\x00R\x00\x00\x00\x07\xa1\x16EventSenderImpl-332664@\xa1\x16event/LOAD_TEST_TENANT@@@\xa3\x18application/octet-stream\x00St\xc1\xa5\x08\xa1\x0corig_adapter\xa1\x09hono-mqtt\xa1\x09device_id\xa1\x13loadTestClient-8004\xa1\x0corig_address\xa1*event/LOAD_TEST_TENANT/loadTestClient-8004\xa1\x15JMS_AMQP_CONTENT_TYPE\xa1\x18application/octet-stream\x00Su\xb0\x00\x00\x02\x00jymfccr6il2bphjnnmypmnn0gavlymwrmuyfip6ifg2mgdl0ns8ext6337q4v5btnuu8mchq7bqjmkg8pdrals8npr4nbc82t6bwe2t7gmqeaj8lxnmj6xmam3c1emf8hbnb0mj58dw2nacq567fdvchbuywqx5smh6ueooeadhuj0nnku3wf4jcnuhl1a4c28nl5iarx1taphc15woiptkt8ape10gwjw4y2tlepdv6bmiwpiqsb3fppchh2i8epv13mtrp8lml3q8smp3w0ch2nruppojtbkv0yxccsosq2cbprcbg6vuvl1mfa2opijcsck6hfmp3f1w2xc3cjcxjmbpqaw727lh8a6dgdy64p7m11p5hcg8iv2h8378mbhs4ssg5gewydyl3n26j6rpu0rltaxc76wh1s51gq7qkq2wormmii83bmtnklf2"... (truncated)
...
````

The last transfer is at `14:22:52.517590`.

Log lines concerning the AMQP links are:
````
$ grep "ALLOW AMQP Attach sender link 'event/LOAD_TEST_TENANT'" qdrouterd.log 
2018-05-29 14:22:51.476722 +0000 POLICY (trace) ALLOW AMQP Attach sender link 'event/LOAD_TEST_TENANT' for user '', rhost '100.116.0.7', vhost 'hono-internal' based on link target name
2018-05-29 14:22:51.487599 +0000 POLICY (trace) ALLOW AMQP Attach sender link 'event/LOAD_TEST_TENANT' for user '', rhost '100.116.0.7', vhost 'hono-internal' based on link target name
2018-05-29 14:22:51.489429 +0000 POLICY (trace) ALLOW AMQP Attach sender link 'event/LOAD_TEST_TENANT' for user '', rhost '100.108.0.8', vhost 'hono-internal' based on link target name
2018-05-29 14:22:51.606669 +0000 POLICY (trace) ALLOW AMQP Attach sender link 'event/LOAD_TEST_TENANT' for user '', rhost '100.116.0.7', vhost 'hono-internal' based on link target name
2018-05-29 14:25:08.786217 +0000 POLICY (trace) ALLOW AMQP Attach sender link 'event/LOAD_TEST_TENANT' for user '', rhost '100.116.0.7', vhost 'hono-internal' based on link target name
````
We have used 4 senders.

> The address in question is a queue (not a topic?) is that right? 

yes, a queue (`event/LOAD_TEST_TENANT`).

**Comment by grs** [comment] 2018-05-30 12:56
>  you can see the corresponding transfer operations by doing a grep 'hono-mqtt' qdrouterd.log

All the transfers I see from that are being sent out from the router to a receiving link. I don't see any log of those messages arriving to the router, which is odd.

**Comment by grs** [comment] 2018-05-30 17:20
Seeing the protocol trace between router and broker will I think help in diagnosing the issue. Perhaps setting PN_TRACE_FRM=1 as an env var for the qdrouterd deployment might avoid the missing log problem (it wouldn't have all the other logging, but I think at this point the protocol traces will be the most helpful if we can get them)

**Comment by calohmn** [comment] 2018-05-31 12:13
Here are more logs:  [log_180531.zip](https://github.com/EnMasseProject/enmasse/files/2058092/log_180531.zip) (with `PN_TRACE_FRM=1` and router log/DEFAULT trace).

In order to correlate log lines between broker and router, the string "EventSenderImpl-[counter]" in the "transfer" log lines can help. It represents the MessageID set by the Hono-MQTT-Adapter instances. 
This MessageID is not unique here though: As we have used 4 Hono-MQTT-Adapter instances with independent counters, the same MessageID could appear for up to 4 different messages.

**Comment by grs** [comment] 2018-05-31 20:45
Thanks, these show the problem clearly. It appears to be a bug in the broker, whereby it is not issuing credit once space opens up on the queue: https://issues.apache.org/jira/browse/ARTEMIS-1898

**Comment by kornys** [comment] 2018-12-10 07:18
@grs artemis issue is resolved, so can we close this issue as well?

**Closed** 2018-12-10 09:04 UTC
