### ISSUE TITLE
standard-authservice get crashloopbackoff status

### ISSUE THREAD

**Issue by aaron0609** [EnMasseProject/enmasse#2617] opened 2019-04-11 02:00 UTC
**Describe the bug**
I followed the 'Documentation for EnMasse on Kubernetes' to deploy the enmasse(verson 0.27.0), after executing the command 'kubectl apply -f install/components/example-authservices/standard-authservice.yaml' I found the pod is never getting up.

Here is the error message from this pod:

> Unable to read the logging configuration from 'file:/opt/jboss/keycloak/standalone/configuration/logging.properties' (java.io.FileNotFoundException: /opt/jboss/keycloak/standalone/configuration/logging.properties (Permission denied))

`[root@XXXX enmasse-0.27.0]# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.3-r1-CCE2.0.17.B003", GitCommit:"df1a90c11bd86b0bdd0685ed8a973500dd9b37ba", GitTreeState:"clean", BuildDate:"2018-12-05T08:01:57Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
`

**To Reproduce**
1. kubectl apply -f install/bundles/enmasse
2. kubectl apply -f install/components/example-plans
3. Wait all pods to be ready
4. kubectl apply -f install/components/example-authservices/standard-authservice.yaml
5. kubectl get pods(Will see standard-authservice in CrashLoopBackOff status)

**Expected behavior**
The status should be shown as 'Running' then we can go to next step

**Screenshots**

**Additional context**
Somehow same steps & package works in my MiniKube test machine but failed in the real k8s cluster

**Comment by aaron0609** [comment] 2019-04-11 02:45
It seems like the permission issue, I have temporarily fixed the issue by logging in that node and grand 777 file permission to all the files under /var/lib/kubelet/pods/MY_POD_ID/volumes/kubernetes.io~empty-dir/keycloak-configuration/, which permission was 0640 (root:root)

Now it works, but I'm still trying to figure out how it happens.

**Comment by k-wall** [comment] 2019-04-15 18:24
@aaron0609 thanks for the report.  I haven't seen the issue you are describing during my tests on minikube.   Have you been previously been deploying earlier versions of EnMasse without seeing this issue?  I ask because 0.27.0 included a Keycloak major upgrade and I'm wondering if this is related.   If I could ask you to try 0.26.5?

Separately, if you are able to attach the complete log from the keycloak pod, that might help.

**Comment by aaron0609** [comment] 2019-04-16 00:46
@k-wall Thanks for your reply. Actually everything goes well on minikube,(Version 0.27.0) no error found during the deployment, and the file permission that I mentioned was all correct on during my tests on minikube.
The issue is the file permission(/var/lib/kubelet/pods/MY_POD_ID/volumes/kubernetes.io~empty-dir/keycloak-configuration/*) would be wrong when deploying the same Enamsse version in kubernetes cluster on the cloud.
So I'm wondering if it's possible that docker images could be different based on different platform(k8s & minikube) for same version(0.27.0).
Regarding to the complete log, very sorry for that as the log has been flushed by rebuilding the pods, I'll also try to reproduce the error on version 0.26.5 on k8s according to your advice.

**Comment by lulf** [comment] 2019-04-22 06:35
@aaron0609 I think I have found the cause for this. The init container setting up the default configuration files are running as root by default on Kubernetes, thereby preventing the Keycloak image, which runs as user 1000, to override these files. I have a fix for this in #2701

**Closed** 2019-04-23 09:20 UTC
