### ISSUE TITLE
Agent unit tests fail on router stats and broker configuration tests

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#1638] opened 2018-09-14 18:00 UTC
I've seen this twice in 2 separate PRs yesterday and today: https://travis-ci.org/EnMasseProject/enmasse/builds/428626428?utm_source=github_status&utm_medium=notification

```
[INFO]   193 passing (31s)
[INFO]   8 failing
[INFO]
[INFO]   1) broker configuration
[INFO]        "after each" hook:
[INFO]      Uncaught Error: connect ECONNRESET 127.0.0.1:45036
[INFO]       at Object._errnoException (util.js:992:11)
[INFO]       at _exceptionWithHostPort (util.js:1014:20)
[INFO]       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
[INFO]
[INFO]   2) router stats
[INFO]        retrieves stats for an anycast address from a single router:
[INFO]      TypeError: Cannot read property 'populate' of undefined
[INFO]       at Context.<anonymous> (test/router_stats.js:264:16)
[INFO]
[INFO]   3) router stats
[INFO]        retrieves stats for a queue from a single router:
[INFO]
[INFO]       AssertionError [ERR_ASSERTION]: 4 == 2
[INFO]       + expected - actual
[INFO]
[INFO]       -4
[INFO]       +2
[INFO]
[INFO]       at /home/travis/build/EnMasseProject/enmasse/agent/test/router_stats.js:317:20
[INFO]       at <anonymous>
[INFO]       at process._tickCallback (internal/process/next_tick.js:188:7)
[INFO]
[INFO]   4) router stats
[INFO]        retrieves stats for an anycast address from multiple routers:
[INFO]
[INFO]       AssertionError [ERR_ASSERTION]: 8 == 4
[INFO]       + expected - actual
[INFO]
[INFO]       -8
[INFO]       +4
[INFO]
[INFO]       at /home/travis/build/EnMasseProject/enmasse/agent/test/router_stats.js:345:20
[INFO]       at <anonymous>
[INFO]       at process._tickCallback (internal/process/next_tick.js:188:7)
[INFO]
[INFO]   5) router stats
[INFO]        retrieves stats for a queue from multiple routers:
[INFO]
[INFO]       AssertionError [ERR_ASSERTION]: 14 == 6
[INFO]       + expected - actual
[INFO]
[INFO]       -14
[INFO]       +6
[INFO]
[INFO]       at /home/travis/build/EnMasseProject/enmasse/agent/test/router_stats.js:395:20
[INFO]       at <anonymous>
[INFO]       at process._tickCallback (internal/process/next_tick.js:188:7)
[INFO]
[INFO]   6) router stats
[INFO]        retrieves propagation for a topic from a single router:
[INFO]
[INFO]       AssertionError [ERR_ASSERTION]: 20 == 100
[INFO]       + expected - actual
[INFO]
[INFO]       -20
[INFO]       +100
[INFO]
[INFO]       at /home/travis/build/EnMasseProject/enmasse/agent/test/router_stats.js:407:20
[INFO]       at <anonymous>
[INFO]       at process._tickCallback (internal/process/next_tick.js:188:7)
[INFO]
[INFO]   7) router stats
[INFO]        updates registries with stats for a queue from a single router:
[INFO]
[INFO]       AssertionError [ERR_ASSERTION]: 16 == 2
[INFO]       + expected - actual
[INFO]
[INFO]       -16
[INFO]       +2
[INFO]
[INFO]       at /home/travis/build/EnMasseProject/enmasse/agent/test/router_stats.js:447:20
[INFO]       at <anonymous>
[INFO]       at process._tickCallback (internal/process/next_tick.js:188:7)
[INFO]
[INFO]   8) router stats
[INFO]        retrieves stats for a queue from a changing set of routers:
[INFO]
[INFO]       AssertionError [ERR_ASSERTION]: 18 == 2
[INFO]       + expected - actual
[INFO]
[INFO]       -18
[INFO]       +2
[INFO]
[INFO]       at /home/travis/build/EnMasseProject/enmasse/agent/test/router_stats.js:466:20
[INFO]       at <anonymous>
[INFO]       at process._tickCallback (internal/process/next_tick.js:188:7)
[INFO]
[INFO]
```

**Comment by grs** [comment] 2018-09-14 18:43
I have too, though I had merged a speculative fix that at the time completed 10 consecutive builds without any failure.

I'm actually a little puzzled by it, particularly by : "TypeError: Cannot read property 'populate' of undefined  at Context.<anonymous> (test/router_stats.js:264:16)", since the object it claims is undefined  (on the first line of the first test) is set as the first line of the beforeEach setup (router = new MockRouter();).

I assumed that the error on the tear down of the last broker_configuration test was having some odd knock on effect. However my speculative fix there was to ensure everything possible exception was caught.

**Comment by grs** [comment] 2018-09-14 18:48
What node version is travis running with btw? 

(I have never been able to reproduce this locally, only seen in CI, and I have run the agent test suite in a loop for more than 200 iterations with no failures.)

**Comment by lulf** [comment] 2018-09-14 19:12
It’s using the version defined in the top level pom.xml , currently 8.11.2 . Should be the exact same version you get if you run mvn test locally.

**Comment by calohmn** [comment] 2018-09-17 11:26
As I recall, the tests don't use the node executable defined via maven yet - see #1394.

**Comment by lulf** [comment] 2018-09-17 11:32
@calohmn I believe this was fixed by @grs a few weeks ago, so the issue can be closed actually. There are a few references to npm_test in Makefile.common (which is not invoked) that I will get rid of.

**Closed** 2018-11-19 10:05 UTC
