### ISSUE TITLE
Unauthorized error detected in version enmasse-0.28.0-rc3

### ISSUE THREAD

**Issue by aaron0609** [EnMasseProject/enmasse#2688] opened 2019-04-17 05:35 UTC
**Describe the bug**
Cannout create standarrd-address-space in version enmasse-0.28.0-rc3 on k8s
Same step works well in both 0.27.2 & 0.27.0

**To Reproduce**
1. Following the steps in https://enmasse.io/documentation/0.28.0-rc2/kubernetes/
2. Go to step 2.3 "Creating address spaces using the command line"
3. kubectl create -f standard-address-space.yaml
4. See error "error: You must be logged in to the server (error when creating "standard-address-space.yaml": Not authorized)"

**Comment by lulf** [comment] 2019-04-17 07:35
Thank you for the bug report. I was able to reproduce the issue on GKE, and I resolved it by running:

`kubectl apply -f install/components/example-roles`
`kubectl create rolebinding admin --clusterrole=enmasse.io:tenant-edit --user=<gcloud-user>`

The reason it worked on 0.27.0 is that in the default setup, RBAC was not enforced on the api-server, which is usually OK when you don't share cluster with multiple tenants.

As an alternative, you can also change the api-server deployment container env ENABLE_RBAC from "true" to "false" to get the old behavior.

**Comment by lulf** [comment] 2019-04-17 12:53
I've found a way we can fix this properly in our api server so that all headers from kube api server is forwarded to the authz check. Will put this in for 0.28.0

**Comment by lulf** [comment] 2019-04-17 18:04
@aaron0609 could you try rc4? It contains a fix for the permissions issue.

**Comment by aaron0609** [comment] 2019-04-18 01:35
> @aaron0609 could you try rc4? It contains a fix for the permissions issue.

I have tried the same steps on rc4, but same error occurred: 
```
[root@XXXXX enmasse-0.28.0-rc4]# kubectl create -f standard-address-space.yaml
error: You must be logged in to the server (error when creating "standard-address-space.yaml": Not authorized)
```
Well it works after disable the RABC as you mentioned.

**Comment by lulf** [comment] 2019-04-18 04:52
Which user are you using to create the address space?

**Comment by lulf** [comment] 2019-04-18 05:17
@aaron0609 FWIW i created a standard GKE cluster and followed the quick start without issues.

**Comment by aaron0609** [comment] 2019-04-18 07:53
> @aaron0609 FWIW i created a standard GKE cluster and followed the quick start without issues. Kubernetes 1.12. Which k8s provider are you using?

I'm using HuaWei Cloud as k8s provider, with Kubernetes v1.11.3

**Comment by lulf** [comment] 2019-04-21 17:57
@aaron0609 What is the best way to create an account there? I am not able to create one as I don't have a phone number in a country where the service is available.

**Comment by aaron0609** [comment] 2019-04-22 00:35
> @aaron0609 There is an international version of Huawei Cloud, here is the link to register your account by email:
[https://console-intl.huaweicloud.com/registerui/public/custom/register.html?locale=en-us&service=https://console-intl.huaweicloud.com/iam/&service=https%3A%2F%2Faccount-intl.huaweicloud.com%2Fusercenter%2F#/register](url)

But actually the issue #2617 is confusing us a lot, we are still trying to read the yaml to understand that problem, this(Unauthorized error) can be temporarily fixed or skipped easily according to your advice.

**Comment by lulf** [comment] 2019-04-22 06:29
@aaron0609 Understood. FWIW, I tried Kubernetes 1.11 on GKE, and my user was not able to create all of the clusterroles needed by EnMasse (som errors during kubectl apply), but I'm not sure if that is the same issue. If the workaround is OK for you (i.e. manually add permissions or disable RBAC) then I will close this.

**Closed by lulf** 2019-04-22 06:29 UTC

**Comment by aaron0609** [comment] 2019-04-23 00:06
@lulf Yes please, and again thanks a lot for your support!
